- name: Install and configure PostgreSQL
  hosts: db_servers
  roles:
    - role: geerlingguy.postgresql
  vars:
    postgresql_python_library: python3-psycopg2
    postgresql_users:
      - name: semaphore
        password: semaphorepass
    postgresql_databases:
      - name: semaphoredb
        owner: semaphore
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: peer }
      - { type: local, database: all, user: all, auth_method: peer }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: "{{ postgresql_auth_method }}" }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: "{{ postgresql_auth_method }}" }


- name: Install and configure Ansible Semaphore with PostgreSQL
  hosts: servers
  become: true
  roles:
    - role: semaphore_postgres
# The variables here are defined as examples (already set by default).
  vars:
    semaphore_version: "latest"
    db_name: "semaphoredb"
    db_user: "semaphore"
    db_passwd: "semaphorepass"
