- name: Install and configure PostgreSQL
  hosts: db_servers
  roles:
    - role: geerlingguy.postgresql
  vars:
    postgresql_python_library: python3-psycopg2
    postgresql_users:
      - name: semaphore
        password: semaphorepass
    postgresql_databases:
      - name: semaphoredb
        owner: semaphore
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: peer }
      - { type: local, database: all, user: all, auth_method: peer }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: "{{ postgresql_auth_method }}" }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: "{{ postgresql_auth_method }}" }


- name: Install and configure Ansible Semaphore with PostgreSQL
  hosts: servers
  become: true

  vars:
    semaphore_version: "latest"
    db_name: "semaphoredb"
    db_user: "semaphore"
    db_passwd: "semaphorepass"
    semaphore_port: 3000
    semaphore_config_path: "/etc/semaphore/config.json"
    semaphore_service_path: "/etc/systemd/system/semaphore.service"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
    - name: Install dependencies
      apt:
        name:
          - curl
          - git
        state: present

    - name: Download Semaphore deb package
      get_url:
        url: https://github.com/semaphoreui/semaphore/releases/download/v2.10.35/semaphore_2.10.35_linux_amd64.deb
        dest: /tmp/semaphore_2.10.35_linux_amd64.deb

    - name: Copy Semaphore systemd service file
      template:
        src: files/semaphore.service.j2
        dest: /etc/systemd/system/semaphore.service
        mode: '0644'

    - name: Ensure Semaphore configuration directory exists
      file:
        path: /etc/semaphore
        state: directory
        owner: root
        mode: '0755'

    - name: Deploy Semaphore configuration file from template
      template:
        src: files/config.json.j2
        dest: "{{ semaphore_config_path }}"
        owner: root
        mode: '0644'

    - name: Install Semaphore from local deb package
      apt:
        deb: /tmp/semaphore_2.10.35_linux_amd64.deb

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Enable and start Semaphore service
      systemd:
        name: semaphore
        enabled: true
        state: started